# Generated by Django 3.2 on 2022-03-01 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0004_speakerpertalk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speakerpertalk",
            options={
                "verbose_name": "Speaker per talk",
                "verbose_name_plural": "speakers per talk",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="is_organizer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_speaker",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="speakerpertalk",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="speakerpertalk",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
