# Generated by Django 3.2 on 2022-03-01 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_auto_20220301_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor level',
                'verbose_name_plural': 'Sponsor levels',
                'db_table': 'sponsor_levels',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='registration_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='asked_for_a_grant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='type',
            field=models.CharField(choices=[('web', 'Website'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('github', 'Github'), ('gitlab', 'Gitlab'), ('reddit', 'Reddit'), ('google', 'Google'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('tumblr', 'Tumblr'), ('vine', 'Vine'), ('flickr', 'Flickr'), ('foursquare', 'Foursquare'), ('other', 'Other')], default='web', max_length=100),
        ),
        migrations.AlterField(
            model_name='talk',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('spanish', 'Spanish'), ('portuguese', 'Portuguese'), ('english/spanish', 'English/Spanish')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='language_slider',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('spanish', 'Spanish'), ('portuguese', 'Portuguese'), ('english/spanish', 'English/Spanish')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_type',
            field=models.CharField(blank=True, choices=[('talk', 'Talk'), ('workshop', 'Workshop'), ('tutorial', 'Tutorial'), ('keynote', 'Keynote'), ('lightning_talk', 'Lightning Talk'), ('open_space', 'Open Space'), ('panel', 'Panel'), ('other', 'Other')], default=None, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='sponsors/logos/')),
                ('confirmed', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('sponsor_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='conferences.sponsorlevel')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'sponsors',
                'db_table': 'sponsors',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('approbed', 'Approbed')], default='requested', max_length=20)),
                ('type', models.CharField(choices=[('transport', 'Transport'), ('housing', 'Housing'), ('food', 'Food'), ('other', 'Other')], default='other', max_length=20)),
                ('reasons', models.TextField(blank=True, default=None, null=True)),
                ('request_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approbed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approbed_date', models.DateField(blank=True, default=None, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('approbed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants_approbed', to='conferences.profile')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants_paid', to='conferences.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='conferences.profile')),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'grants',
                'db_table': 'grants',
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('address_line_2', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='State/Province/Region')),
                ('zip_code', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_information', to='conferences.country')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_information', to='conferences.profile')),
            ],
            options={
                'verbose_name': 'ContactInformation',
                'verbose_name_plural': 'contact_information',
                'db_table': 'contact_information',
            },
        ),
    ]
