# Generated by Django 3.2 on 2022-03-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0007_staticpage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staticpage",
            options={
                "verbose_name": "Static page",
                "verbose_name_plural": "static pages",
            },
        ),
        migrations.AddField(
            model_name="speakerpertalk",
            name="speaker_order",
            field=models.IntegerField(default=0),
        ),
    ]
