# Generated by Django 3.2 on 2022-03-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0010_auto_20220302_2009"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Resource",
        ),
    ]
