# Generated by Django 3.2 on 2022-03-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0013_auto_20220302_2135"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="slug",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
