# Generated by Django 3.2 on 2022-03-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0014_staticpage_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticpage",
            name="slug",
            field=models.SlugField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
