# Generated by Django 3.2 on 2022-05-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0023_auto_20220521_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
