# Generated by Django 3.2 on 2022-06-19 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0035_auto_20220618_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='conferences.event')),
                ('static_page', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferences.staticpage')),
            ],
            options={
                'verbose_name': 'EventLink',
                'verbose_name_plural': 'Event links',
                'db_table': 'event_links',
            },
        ),
    ]
