# Generated by Django 3.2 on 2022-08-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0043_register_all_user_active_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="sort_weight",
            field=models.IntegerField(default=0),
        ),
    ]
