# Generated by Django 3.2 on 2022-09-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0045_auto_20220912_0016"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="lat",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AddField(
            model_name="room",
            name="long",
            field=models.CharField(default="", max_length=25),
        ),
    ]
